[versions]
android = "7.2.1"
kotlin = "1.7.10"
dagger = "2.33"
compose = "1.2.1"

[libraries]
android-application-plugin = { module = "com.android.application:com.android.application.gradle.plugin", version.ref = "android" }
android-library-plugin = { module = "com.android.library:com.android.library.gradle.plugin", version.ref = "android" }

kotlin-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

dagger = { module = "com.google.dagger:dagger", version.ref = "dagger" }
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }

androidx-core-ktx = { module = "androidx.core:core-ktx", version = "1.8.0" }
android-lifecycle = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version = "2.3.1" }

compose-activity = { module = "androidx.activity:activity-compose", version = "1.5.1" }
compose-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version = "2.5.1" }

compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
compose-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
compose-junit = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }

volley = { module = "com.android.volley:volley", version = "1.2.1" }

junit = { module = "junit:junit", version = "4.13.2" }
androidx-junit = { module = "androidx.test.ext:junit", version = "1.1.3" }
espresso = { module = "androidx.test.espresso:espresso-core", version = "3.4.0" }

# internal
plugin-code-check = { module = "pro.yakuraion.plugins.codecheck:code-check", version = "1.0-SNAPSHOT" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android" }
android-library = { id = "com.android.library", version.ref = "android" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
