[versions]
android = "7.2.1"
kotlin = "1.7.0"

[libraries]
android-application-plugin = { module = "com.android.application:com.android.application.gradle.plugin", version.ref = "android" }
android-library-plugin = { module = "com.android.library:com.android.library.gradle.plugin", version.ref = "android" }

kotlin-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

androidx-core-ktx = { module = "androidx.core:core-ktx", version = "1.8.0" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version = "1.4.2" }
material = { module = "com.google.android.material:material", version = "1.6.1" }

# tests
junit = { module = "junit:junit", version = "4.13.2" }
androidx-junit = { module = "androidx.test.ext:junit", version = "1.1.3" }
espresso = { module = "androidx.test.espresso:espresso-core", version = "3.4.0" }

# internal
plugin-code-check = { module = "pro.yakuraion.plugins.codecheck:code-check", version = "1.0-SNAPSHOT" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android" }
android-library = { id = "com.android.library", version.ref = "android" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
